name: spark_dbt_tikas
version: "1.0.0"
config-version: 2

profile: spark_dbt_tikas

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  spark_dbt_tikas:
    staging:
      +materialized: view
    gold:
      +materialized: table
      +engine: OLAP
      +distributed_by:
        - file_name
      +buckets: 4
      +properties:
        replication_num: "1"
